title: BookYearning
description: > # this means to ignore newlines until "baseurl:"
  Don't look too hard, this is all under construction!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yayforbooks.randomlyrecursive.com" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: Maria Morabe
  last_name: Morabe
  avatar: '/images/avatar.jpeg'
  github_username:  mlmorabe 
  email: mariayearnsforbooks@gmail.com
  twitter_username: yayforbooks
  instagram_username: standardhonor
  itch: yayforbooks
  logo: '/images/lotus.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


