title: BookYearning
description: > # this means to ignore newlines until "baseurl:"
  A place for my thoughts on books, games, and whatever else strikes my fancy. Wild tone shifts because that's who I am as a person. (Don't look too hard, this is all under construction.)
baseurl:  # the subpath of your site, e.g. /blog
url: http://yayforbooks.randomlyrecursive.com # the base hostname & protocol for your site, e.g. http://example.com
fullurl: http://yayforbooks.randomlyrecursive.com


author:
  name: Maria M.
  last_name: M.
  avatar: '/images/avatar.jpeg'
  github_username:  mlmorabe 
  email: mariayearnsforbooks@gmail.com
  twitter_username: yayforbooks
  instagram_username: standardhonor
  itch: yayforbooks
  logo: '/images/lotus.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

plugins:
  - jekyll-feed
  - jekyll-gallery-generator


# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: bookyearning

gallery:
  dir: photos               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Photos"           # Title for gallery index page
  title_prefix: "Photos: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  lightbox: true
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    creations:
      name: "things i've made"
      info:
        desc: "sometimes I make things"
    life:
      info:
        desc: "slices of life" # Info fields can be used in custom templates.
    lotus:
      info:
        desc: "just the best cat"
    film:
      name: "film photography"
      info:
        desc: "film photography experiments"