title: BookYearning
description: > # this means to ignore newlines until "baseurl:"
  (don't look too hard, this is all under construction!) A place for my thoughts on books, games, and whatever else strikes my fancy
baseurl:  # the subpath of your site, e.g. /blog
url: http://yayforbooks.randomlyrecursive.com # the base hostname & protocol for your site, e.g. http://example.com
fullurl: http://yayforbooks.randomlyrecursive.com


author:
  name: Maria Morabe
  last_name: Morabe
  avatar: '/images/avatar.jpeg'
  github_username:  mlmorabe 
  email: mariayearnsforbooks@gmail.com
  twitter_username: yayforbooks
  instagram_username: standardhonor
  itch: yayforbooks
  logo: '/images/lotus.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html

plugins:
  - jekyll-feed

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: bookyearning